### ISSUE TITLE
9.5 Competency checklist

### ISSUE THREAD

**Issue by eda-waffler** [piwakawaka-2016/piwakawaka-2016#1556]
# 9.5 Competency checklist

This is a checklist of the core competencies you need for bootcamp :seedling:

## Command line
I can:
- [ ] navigate
- [ ] create files
- [ ] rename files
- [ ] move files

## Git
I can:
- [ ] clone
- [ ] stage & push
- [ ] pull
- [ ] branch
- [ ] handle pull requests
- [ ] make good commit messages
- [ ] make small frequent commits
- [ ] view my git log

## Design
I can:
- [ ] create wireframes
- [ ] 'boxify' my wireframes ready for HTML & CSS creation

## HTML
I can:
- [ ] create elements
- [ ] use tag attributes
- [ ] use semantic HTML
- [ ] create a valid HTML page structure
- [ ] perfectly indent my HTML
- [ ] create HTML from wireframes
- [ ] use HTML **only** for content, not styling
- [ ] abstain from inline styling
- [ ] use Content Delivery Networks (CDNs)

## CSS
I can:
- [ ] link CSS file to HTML file
- [ ] use element selectors
- [ ] use class selectors
- [ ] use good reusable class names
- [ ] use child and parent selectors
- [ ] use CSS specificity
- [ ] use the cascading nature of CSS
- [ ] apply colors
- [ ] apply font styling
- [ ] normalise CSS across browsers
- [ ] use Google Dev Tools to inspect and test CSS
- [ ] handle images with CSS
- [ ] position elements with
  - [ ] fixed position
  - [ ] absolute position
  - [ ] relative position
  - [ ] static position
- [ ] use flexbox to position elements
- [ ] use the box model to position and style elements
- [ ] use media queries
- [ ] use mobile first styling
- [ ] use a grid framework to create a responsive page

## DOM
I can:
- [ ] inspect the DOM in Chrome DevTools

## JS
I can:
- [ ] link JS file to HTML file
- [ ] use all the JS datatypes
- [ ] declare variables
- [ ] manipulate strings
- [ ] manipulate arrays
- [ ] manipulate objects
- [ ] use prompts and alerts
- [ ] use comments in my code
- [ ] use if/else statements
- [ ] use switch statements
- [ ] use basic regular expressions
- [ ] use 'truthy' and 'falsy' values
- [ ] use vanilla JS to manipulate the DOM
- [ ] use jQuery to manipulate the DOM
- [ ] use console.log
- [ ] perfectly indent my JS
- [ ] use and understand scope
- [ ] declare functions
- [ ] explain the difference between arguments and parameters
- [ ] return things from functions
- [ ] use `while`/`do` loops
- [ ] use `for` loops
- [ ] use `map`
- [ ] use `reduce`
- [ ] use `filter`
- [ ] give my functions and variables good descriptive names
- [ ] create single responsibility functions

## Problem Solving
I can:
- [ ] pseudocode
- [ ] try some code
- [ ] isolate the bug
- [ ] debug - 
  - [ ] talk to my rubber ducky
  - [ ] read the error messages
  - [ ] console.log
  - [ ] google
- [ ] ask my cohort
- [ ] ask a coach
- [ ] reflect and learn from my experience
- [ ] recognise when I need to ask for help

## Learning
I can:
- [ ] identify how I learn best
- [ ] optimise my learning
- [ ] prioritise process over product

## Habits
I have developed habits of:
- [ ] reflecting
- [ ] tidying
- [ ] playing
- [ ] perservering
- [ ] exploring
- [ ] communication
- [ ] equinimity
- [ ] honing
- [ ] sharing

## Engineering Empathy
I can increasingly:
- [ ] meditate (even if just a couple of minutes)
- [ ] observe my patterns of thought
- [ ] hold attention
- [ ] apply mindfulness to my interactions with my cohort and Dev Academy
- [ ] journal
- [ ] body scan
- [ ] stop identifying with my emotions
- [ ] identify my values
- [ ] use listening and looping
- [ ] use empathic listening
- [ ] communicate openly and honestly
- [ ] give valuable, kind and honest feedback
- [ ] gracefully recieve feedback
- [ ] hold integrity
- [ ] hold kindness
- [ ] hold effort

**Comment by chris-daynes** [comment]
Although I ticked all the boxes, when ever the word perfectly is used I hesitate. I mean, does anyone really achieve perfection or is it just something that one constantly strives for.  Some of the smartest people I know are constantly striving for perfection. May I never call myself and expert!
